Repository johngeorgewright/runtyping, pull requests merged in 2021-09, with the labels that each got.

#59 Document using runtyping from a script
  README.md
Labels: documentation

#61 feat: reuse type aliases
  src/typeWriter/generateOrReuseType.ts
  test/tuple.test.ts
Labels: enhancement

#62 chore: runtypes should be a peerdependency
  package.json
Labels: breaking change

#63 Nullable types
  README.md
  src/generate.ts
  src/typeWriter/factory.ts
  src/typeWriter/function.ts
  src/typeWriter/object.ts
  test/function.test.ts
  test/generateFixture.ts
  test/maxItems.test.ts
  test/minItems.test.ts
  test/null.test.ts
  test/null.ts
  test/optional.test.ts
  test/schema.test.ts
Labels: enhancement

#66 refactor: generator
  README.md
  src/Generator.ts
  src/cli.ts
  src/generate.ts
  src/index.ts
  src/typeWriter/index.ts
  test/generateFixture.ts
  test/maxItems.test.ts
  test/minItems.test.ts
  test/schema.test.ts
Labels: breaking change

#71 feat: allow singular target & source type
  README.md
  package.json
  runtyping.yml
  src/cli.ts
  src/runtypes.ts
  src/types.ts
Labels: enhancement

#72 feat: generate a json schema for runtyping.yml
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  runtyping.schema.json
Labels: enhancement
